// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Zoo_Management.Migrations
{
    [DbContext(typeof(ZooManagementDbContext))]
    [Migration("20250312123526_animaltable")]
    partial class animaltable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfPassing")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfZooEntry")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfZooLeaving")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EnclosureNameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnclosureNameId");

                    b.ToTable("Animal");
                });

            modelBuilder.Entity("Models.Enclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxNumberOfOccupants")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Enclosure");
                });

            modelBuilder.Entity("Models.Animal", b =>
                {
                    b.HasOne("Models.Enclosure", "EnclosureName")
                        .WithMany()
                        .HasForeignKey("EnclosureNameId");

                    b.Navigation("EnclosureName");
                });
#pragma warning restore 612, 618
        }
    }
}
